# Kubernetes Alias Generator Config
#
# Written by Mutlu Polatcan
# 30.06.2020
# ==============================================

output_filename: ".k8s_aliases"

api_resources:
  "no": "no"
  pv: "pv"
  pvc: "pvc"
  sec: "secret"
  po: "po"
  svc: "svc"
  ing: "ing"
  dep: "deploy"
  sts: "sts"
  hpa: "hpa"
  cj: "cj"
  j: "jobs"


api_cmds:
  g:
    cmd: "get"
    opts:
      all:
        opt: "--all-namespaces"
        exclude_resources: ["no"]
      w:
        opt: "--watch"
        exclude_resources: ["pv", "pvc", "sec", "svc", "ing"]
        exclude_opts: ["ojson", "oyaml"]
      sl:
        opt: "--show-labels"
        exclude_opts: ["ojson", "oyaml"]
      l:
        opt: "-l ${}"
        parametric: true
        exclude_resources: ["no"]
      ns:
        opt: "-n ${}"
        parametric: true
        exclude_resources: ["no"]
      owide:
        opt: "-o wide"
        exclude_opts: ["oyaml", "ojson"]
      oyaml:
        opt: "-o yaml"
        exclude_opts: ["w", "owide", "ojson"]
      ojson:
        opt: "-o json"
        exclude_opts: ["w", "owide", "oyaml"]

  rm:
    cmd: "delete"
    opts:
      all:
        opt: "--all-namespaces"
      l:
        opt: "-l ${}"
        parametric: true
      ns:
        opt: "-n ${}"
        parametric: true
    exclude_resources: ["no"]

  d:
    cmd: "describe"
    opts:
      l:
        opt: "-l ${}"
        parametric: true
      ns:
        opt: "-n ${}"
        parametric: true

  e:
    cmd: "edit"
    opts:
      ns:
        opt: "-n ${}"
        parametric: true
