# Kubernetes Alias Generator Config
#
# Written by Mutlu Polatcan
# 30.06.2020
# ==============================================

output_filename: ".k8s_aliases"

api_resources:
  "no": "no"
  pv: "pv"
  pvc: "pvc"
  sec: "secret"
  po: "po"
  svc: "svc"
  ing: "ing"
  dep: "deploy"
  sts: "sts"
  hpa: "hpa"
  cj: "cj"
  j: "jobs"
  cm: "cm"


api_cmds:
  g:
    cmd: "get"
    opts:
      nsall:
        opt: "--all-namespaces"
        exclude_resources:
          - "no"
        exclude_opts:
          - "ns"
      # ========================
      all:
        opt: "--all"
        exclude_resources:
          - "no"
      # ========================
      w:
        opt: "--watch"
        exclude_resources:
          - "pv"
          - "pvc"
          - "cm"
          - "sec"
          - "svc"
          - "ing"
        exclude_opts:
          - "ojson"
          - "oyaml"
      # ========================
      sl:
        opt: "--show-labels"
        exclude_opts:
          - "ojson"
          - "oyaml"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
        exclude_resources:
          - "no"
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
        exclude_opts:
          - "all"
        exclude_resources:
          - "no"
      # ========================
      owide:
        opt: "-o wide"
        exclude_opts:
          - "oyaml"
          - "ojson"
      # ========================
      oyaml:
        opt: "-o yaml"
        exclude_opts:
          - "w"
          - "owide"
          - "ojson"
      # ========================
      ojson:
        opt: "-o json"
        exclude_opts:
          - "w"
          - "owide"
          - "oyaml"
      # ========================

# ==============================================================

  rm:
    cmd: "delete"
    opts:
      nsall:
        opt: "--all-namespaces"
        exclude_opts:
          - "ns"
      # ========================
      all:
        opt: "--all"
        exclude_resources:
          - "no"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
        exclude_opts:
          - "all"
      # ========================
      f:
        opt: "-f ${}"
        parametric: true
        exclude_opts:
          - "k"
        resource_specific: false
      # ========================
      k:
        opt: "-k ${}"
        parametric: true
        exclude_opts:
          - "f"
        resource_specific: false
        # ========================
    exclude_resources:
      - "no"

# ==============================================================

  d:
    cmd: "describe"
    opts:
      all:
        opt: "--all-namespaces"
        exclude_opts:
          - "ns"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
        exclude_opts:
          - "all"
      # ========================
      r:
        opt: "--recursive"
      # ========================
      f:
        opt: "-f ${}"
        parametric: true
        exclude_opts:
          - "k"
        resource_specific: false
      # ========================
      k:
        opt: "-k ${}"
        parametric: true
        exclude_opts:
          - "f"
        resource_specific: false
        # ========================
    exclude_resources:
      - "no"

# ==============================================================

  e:
    cmd: "edit"
    opts:
      ns:
        opt: "-n ${}"
        parametric: true
      # ========================
    exclude_resources:
      - "no"

# ==============================================================

  log:
    cmd: "logs"
    opts:
      f:
        opt: "-f"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
      # ========================
    resource_specific: false

# ==============================================================

  a:
    cmd: "apply"
    opts:
      f:
        opt: "-f ${}"
        parametric: true
        exclude_opts:
          - "k"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
      # ========================
      k:
        opt: "-k ${}"
        parametric: true
        exclude_opts:
          - "f"
      # ========================
      r:
        opt: "--recursive"
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
      # ========================
    resource_specific: false

# ==============================================================

  pw:
    cmd: "port-forward"
    resource_specific: false

# ==============================================================

  x:
    cmd: "exec"
    opts:
      it:
        opt: "-it ${}"
        parametric: true
      cmd:
        opt: "-- ${}"
        parametric: true
    resource_specific: false

# ================================================================

  c:
    cmd: "create"
    opts:
      f:
        opt: "-f ${}"
        parametric: true
        exclude_opts:
          - "k"
      # ========================
      l:
        opt: "-l ${}"
        parametric: true
      # ========================
      k:
        opt: "-k ${}"
        parametric: true
        exclude_opts:
          - "f"
      # ========================
      r:
        opt: "--recursive"
      # ========================
      ns:
        opt: "-n ${}"
        parametric: true
      # ========================
    resource_specific: false